# Generated by Django 6.1 on 2026-10-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_bearing_product_bus_width_product_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_name',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
